#!/usr/bin/env python3
"""Converts embedded_rules.json into a C++ header with the raw bytes,
   for compile-time inclusion in the firmware image.

Accepts either:
  - an MB mapping document (top-level non-empty `rules` array), or
  - a full web profile export (rules under `mbMapping.rules`).
"""
import json
import pathlib
import sys

SRC = pathlib.Path(__file__).parent.parent / "firmware/StrollerController/embedded_rules.json"
DST = pathlib.Path(__file__).parent.parent / "firmware/StrollerController/EmbeddedRules.h"


def resolve_mapping(parsed: dict) -> dict:
    """Return the mapping object that should be baked into flash."""
    rules = parsed.get("rules")
    if isinstance(rules, list) and len(rules) > 0:
        return parsed

    mb = parsed.get("mbMapping")
    if isinstance(mb, dict):
        mb_rules = mb.get("rules")
        if isinstance(mb_rules, list) and len(mb_rules) > 0:
            out = dict(mb)
            # Allow forceOverride on the profile root (not only inside mbMapping).
            if "forceOverride" in parsed and "forceOverride" not in out:
                out["forceOverride"] = parsed["forceOverride"]
            return out

    return parsed


def main():
    if not SRC.exists():
        DST.write_text(
            "// Auto-generated. No embedded_rules.json found at build time.\n"
            "#pragma once\n"
            "static const bool kHasEmbeddedRules = false;\n"
            "static const char kEmbeddedRulesJson[] = \"\";\n"
        )
        print("[embed_rules] no embedded_rules.json found — emitting empty placeholder")
        return

    try:
        parsed = json.loads(SRC.read_text(encoding="utf-8"))
    except Exception as e:
        print(f"[embed_rules] ERROR: embedded_rules.json is not valid JSON: {e}", file=sys.stderr)
        sys.exit(1)

    if not isinstance(parsed, dict):
        print("[embed_rules] ERROR: embedded_rules.json must be a JSON object", file=sys.stderr)
        sys.exit(1)

    mapping = resolve_mapping(parsed)
    rules = mapping.get("rules")
    if not isinstance(rules, list) or len(rules) == 0:
        print(
            "[embed_rules] ERROR: no non-empty 'rules' array at root or under mbMapping\n"
            "  Tip: use data.mbMapping from a web export, or paste the full profile — "
            "this script will unwrap mbMapping.",
            file=sys.stderr,
        )
        sys.exit(1)

    # Completeness check: this embedded copy is the fallback the firmware
    # silently loads whenever SPIFFS-persisted rules are missing or corrupt
    # (see docs/rules-psram-runbook.md). A fallback with no colors/segments
    # produces stock/wrong-looking output with no way to tell why, since it's
    # compiled into the binary rather than visible as a bad file on disk.
    # Warn loudly rather than staying silent; do not hard-fail (rules-only
    # embeds can be intentional).
    colors = mapping.get("colors")
    segments = mapping.get("segments")
    warnings = []
    # Profile exports store colors as a hex array; BLE/firmware mapping may
    # use an index-keyed object. Either non-empty collection is complete.
    colors_ok = isinstance(colors, (dict, list)) and len(colors) > 0
    segments_ok = isinstance(segments, (dict, list)) and len(segments) > 0
    if not colors_ok:
        warnings.append("'colors' is missing or empty")
    if not segments_ok:
        warnings.append("'segments' is missing or empty")
    if warnings:
        print(
            "[embed_rules] WARNING: embedding a fallback ruleset that is INCOMPLETE:\n"
            + "\n".join(f"  - {w}" for w in warnings)
            + "\n  This is the firmware's silent fallback if SPIFFS rules ever fail to "
              "load — an incomplete embed here means a field failure falls back to "
              "wrong/default colors with no serial-log-free way to notice.\n"
              "  If this is intentional (e.g. rules-only test embed), ignore this warning.\n"
              "  Otherwise: re-export the full profile from the web app (not a partial/\n"
              "  rules-only export) before re-running this script.",
            file=sys.stderr,
        )

    # Compact JSON for flash size; keep Unicode as-is.
    raw = json.dumps(mapping, separators=(",", ":"), ensure_ascii=False)
    if mapping is not parsed:
        print(
            f"[embed_rules] unwrapped mbMapping from profile export "
            f"({len(SRC.read_bytes())} → {len(raw.encode('utf-8'))} bytes)"
        )

    escaped = (
        raw.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "")
    )
    DST.write_text(
        "// Auto-generated by scripts/embed_rules.py — do not edit by hand.\n"
        "#pragma once\n"
        "static const bool kHasEmbeddedRules = true;\n"
        f'static const char kEmbeddedRulesJson[] = "{escaped}";\n'
    )
    color_count = len(colors) if isinstance(colors, (dict, list)) else 0
    print(
        f"[embed_rules] embedded {len(raw.encode('utf-8'))} bytes "
        f"({len(rules)} rules, {color_count} colors)"
    )


if __name__ == "__main__":
    main()
