#!/usr/bin/env python3
"""Converts embedded_rules.json into a C++ header with the raw bytes,
   for compile-time inclusion in the firmware image."""
import json
import pathlib
import sys

SRC = pathlib.Path(__file__).parent.parent / "firmware/StrollerController/embedded_rules.json"
DST = pathlib.Path(__file__).parent.parent / "firmware/StrollerController/EmbeddedRules.h"


def main():
    if not SRC.exists():
        DST.write_text(
            "// Auto-generated. No embedded_rules.json found at build time.\n"
            "#pragma once\n"
            "static const bool kHasEmbeddedRules = false;\n"
            "static const char kEmbeddedRulesJson[] = \"\";\n"
        )
        print("[embed_rules] no embedded_rules.json found — emitting empty placeholder")
        return

    raw = SRC.read_bytes()
    try:
        parsed = json.loads(raw)
    except Exception as e:
        print(f"[embed_rules] ERROR: embedded_rules.json is not valid JSON: {e}", file=sys.stderr)
        sys.exit(1)
    if not isinstance(parsed.get("rules"), list) or len(parsed["rules"]) == 0:
        print("[embed_rules] ERROR: embedded_rules.json has no non-empty 'rules' array", file=sys.stderr)
        sys.exit(1)

    escaped = (
        raw.decode("utf-8")
        .replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "")
    )
    DST.write_text(
        "// Auto-generated by scripts/embed_rules.py — do not edit by hand.\n"
        "#pragma once\n"
        "static const bool kHasEmbeddedRules = true;\n"
        f'static const char kEmbeddedRulesJson[] = "{escaped}";\n'
    )
    print(
        f"[embed_rules] embedded {len(raw)} bytes from embedded_rules.json "
        f"({len(parsed['rules'])} rules)"
    )


if __name__ == "__main__":
    main()
